### Data augmentation using autoencoders
#### Edgar Acuna
#### July 2021

In [1]:
import warnings
warnings.filterwarnings('ignore')
import tensorflow as tf
import keras
from keras.models import Model, load_model
from keras.layers import Input, Dense
from keras.callbacks import ModelCheckpoint, TensorBoard
from keras import regularizers
from sklearn.preprocessing import  StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.io
%matplotlib inline
mat = scipy.io.loadmat('C:/Users/eacun/Downloads/dataset55_release2.mat')
%matplotlib inline

In [2]:
y=mat['labels']

In [3]:
df=mat['spectra']
df=pd.DataFrame(df)
print(df.shape)

(49500, 1701)


In [4]:
ys=mat['substrateIDs']

In [5]:
subs=mat['substrateSpectra']
subs=pd.DataFrame(subs)
#subs

In [6]:
dfset2=df.copy()
dfset2['Analyte']=y
dfset2['substrate']=ys
dfset2.tail()

0         1         2         3         4         5         6  \
49495  0.037553  0.028473  0.036529  0.036093  0.016089  0.032855  0.029435   
49496  0.029870  0.032666  0.032152  0.033202  0.033766  0.031824  0.029444   
49497  0.017774  0.024707  0.040428  0.023651  0.021570  0.033614  0.025827   
49498  0.031123  0.029965  0.032992  0.033308  0.031816  0.031922  0.033099   
49499  0.032366  0.032454  0.032383  0.032554  0.032657  0.032594  0.032640   

              7         8         9  ...      1693      1694      1695  \
49495  0.028151  0.030395  0.024624  ...  0.531353  0.543420  0.535867   
49496  0.035251  0.034372  0.031036  ...  0.544204  0.544876  0.545065   
49497  0.023418  0.016353  0.044331  ...  0.534933  0.549713  0.550770   
49498  0.032652  0.032133  0.030951  ...  0.542406  0.542487  0.540469   
49499  0.032542  0.032122  0.031636  ...  0.543924  0.543932  0.543901   

           1696      1697      1698      1699      1700  Analyte  substrate  
49495  0.538912  0.536256  0.547188  0.539499  0.553740       55          8  
49496  0.546364  0.542205  0.539576  0.539069  0.543899       55          8  
49497  0.546890  0.538551  0.528992  0.533424  0.541260       55          8  
49498  0.541910  0.542449  0.541800  0.539430  0.542759       55          8  
49499  0.543841  0.543787  0.543787  0.543832  0.543866       55          8  

[5 rows x 1703 columns]

### Extracting the nine substrates

In [7]:
dfsub1=dfset2[dfset2['substrate']==1]
dfsub2=dfset2[dfset2['substrate']==2]
dfsub3=dfset2[dfset2['substrate']==3]
dfsub4=dfset2[dfset2['substrate']==4]
dfsub5=dfset2[dfset2['substrate']==5]
dfsub6=dfset2[dfset2['substrate']==6]
dfsub7=dfset2[dfset2['substrate']==7]
dfsub8=dfset2[dfset2['substrate']==8]
dfsub9=dfset2[dfset2['substrate']==9]
#dfset1=pd.DataFrame(dfset1)
df['Analyte']=y
df['substrate']=ys
#df.iloc[20000:20006,:]
#yt=dfset5["Analyte"]
dfsub9.head()
#dfset5.shape}

0         1         2         3         4         5         6  \
38500  0.024015  0.039861  0.034675  0.029205  0.032690  0.021443  0.015242   
38501  0.024314  0.024558  0.027552  0.029469  0.028968  0.027818  0.026456   
38502  0.020178  0.018663  0.022727  0.030922  0.033027  0.025272  0.020529   
38503  0.021856  0.023824  0.021751  0.026594  0.023305  0.025255  0.022746   
38504  0.022338  0.022713  0.027130  0.027351  0.026226  0.024680  0.023145   

              7         8         9  ...      1693      1694      1695  \
38500  0.016019  0.017425  0.021906  ...  0.033070  0.021220  0.038450   
38501  0.025333  0.025255  0.024868  ...  0.028214  0.027968  0.027430   
38502  0.033971  0.030392  0.021519  ...  0.027900  0.040675  0.020609   
38503  0.022709  0.024891  0.024903  ...  0.025364  0.024616  0.027775   
38504  0.023026  0.021459  0.023483  ...  0.024759  0.027120  0.025498   

           1696      1697      1698      1699      1700  Analyte  substrate  
38500  0.042687  0.026959  0.009430  0.014245  0.021775        1          9  
38501  0.027127  0.026760  0.026210  0.025938  0.025846        1          9  
38502  0.023321  0.015935  0.023401  0.032025  0.021270        1          9  
38503  0.020910  0.022473  0.021650  0.019606  0.017557        1          9  
38504  0.024313  0.024917  0.024866  0.022272  0.021763        1          9  

[5 rows x 1703 columns]

In [8]:
mdfsub1=dfsub1.iloc[:,0:1701]
mdfsub2=dfsub2.iloc[:,0:1701]
mdfsub3=dfsub3.iloc[:,0:1701]
mdfsub4=dfsub4.iloc[:,0:1701]
mdfsub5=dfsub5.iloc[:,0:1701]
mdfsub6=dfsub6.iloc[:,0:1701]
mdfsub7=dfsub7.iloc[:,0:1701]
mdfsub8=dfsub8.iloc[:,0:1701]
mdfsub9=dfsub9.iloc[:,0:1701]

In [9]:
s1=subs.loc[0,:]
s2=subs.loc[1,:]
s3=subs.loc[2,:]
s4=subs.loc[3,:]
s5=subs.loc[4,:]
s6=subs.loc[5,:]
s7=subs.loc[6,:]
s8=subs.loc[7,:]
s9=subs.loc[8,:]

In [10]:
modsub1=mdfsub1.apply(lambda x : x -(np.sum(np.array(x)*np.array(s1))/np.sum(np.array(s1)*np.array(s1)))*s1,axis=1)
modsub2=mdfsub2.apply(lambda x : x -(np.sum(np.array(x)*np.array(s2))/np.sum(np.array(s2)*np.array(s2)))*s2,axis=1)
modsub3=mdfsub3.apply(lambda x : x -(np.sum(np.array(x)*np.array(s3))/np.sum(np.array(s3)*np.array(s3)))*s3,axis=1)
modsub4=mdfsub4.apply(lambda x : x -(np.sum(np.array(x)*np.array(s4))/np.sum(np.array(s4)*np.array(s4)))*s4,axis=1)
modsub5=mdfsub5.apply(lambda x : x -(np.sum(np.array(x)*np.array(s5))/np.sum(np.array(s5)*np.array(s5)))*s5,axis=1)
modsub6=mdfsub6.apply(lambda x : x -(np.sum(np.array(x)*np.array(s6))/np.sum(np.array(s6)*np.array(s6)))*s6,axis=1)
modsub7=mdfsub7.apply(lambda x : x -(np.sum(np.array(x)*np.array(s7))/np.sum(np.array(s7)*np.array(s7)))*s7,axis=1)
modsub8=mdfsub8.apply(lambda x : x -(np.sum(np.array(x)*np.array(s8))/np.sum(np.array(s8)*np.array(s8)))*s8,axis=1)
modsub9=mdfsub9.apply(lambda x : x -(np.sum(np.array(x)*np.array(s9))/np.sum(np.array(s9)*np.array(s9)))*s9,axis=1)

### Data centered by substrates background

In [11]:
subdf=[modsub1,modsub2,modsub3,modsub4,modsub5,modsub6,modsub7,modsub8,modsub9]
cent_subs=pd.concat(subdf)
cent_subs.head()

0         1         2         3         4         5         6     \
0  0.001835  0.000878  0.000793  0.000247  0.000728  0.001072  0.002347   
1  0.003758 -0.002548  0.006330 -0.011134  0.000164  0.005120 -0.002903   
2  0.001106  0.001177  0.001245  0.001310  0.001369  0.001383  0.001337   
3  0.000363  0.003034  0.003668  0.002877  0.002038  0.000546  0.002638   
4  0.003795  0.009750  0.001765  0.005447  0.004424  0.003195  0.001814   

       7         8         9     ...      1691      1692      1693      1694  \
0  0.000115  0.000966  0.001123  ... -0.003352 -0.004829 -0.003905 -0.002224   
1 -0.003049 -0.006294  0.003996  ... -0.010454  0.004719 -0.009114 -0.001578   
2  0.001292  0.001355  0.001509  ... -0.003437 -0.003414 -0.003390 -0.003366   
3 -0.002580 -0.000733 -0.003121  ... -0.002536 -0.007373 -0.000276 -0.002173   
4 -0.004758  0.005961  0.005176  ... -0.003264  0.001135 -0.008510 -0.000614   

       1695      1696      1697      1698      1699      1700  
0 -0.002386 -0.003332 -0.003701 -0.003463 -0.004489 -0.005034  
1 -0.002636 -0.001219  0.000561 -0.004356  0.002053 -0.007237  
2 -0.003341 -0.003316 -0.003289 -0.003263 -0.003236 -0.003209  
3 -0.007754 -0.006247 -0.003583 -0.004043 -0.002472 -0.008282  
4 -0.004077 -0.013175 -0.004247 -0.002622 -0.000083 -0.003888  

[5 rows x 1701 columns]

### Normalizing the spectra

In [12]:
# Using sklearn
from sklearn.preprocessing import normalize
b=cent_subs.iloc[:,0:1701]
b.head()

0         1         2         3         4         5         6     \
0  0.001835  0.000878  0.000793  0.000247  0.000728  0.001072  0.002347   
1  0.003758 -0.002548  0.006330 -0.011134  0.000164  0.005120 -0.002903   
2  0.001106  0.001177  0.001245  0.001310  0.001369  0.001383  0.001337   
3  0.000363  0.003034  0.003668  0.002877  0.002038  0.000546  0.002638   
4  0.003795  0.009750  0.001765  0.005447  0.004424  0.003195  0.001814   

       7         8         9     ...      1691      1692      1693      1694  \
0  0.000115  0.000966  0.001123  ... -0.003352 -0.004829 -0.003905 -0.002224   
1 -0.003049 -0.006294  0.003996  ... -0.010454  0.004719 -0.009114 -0.001578   
2  0.001292  0.001355  0.001509  ... -0.003437 -0.003414 -0.003390 -0.003366   
3 -0.002580 -0.000733 -0.003121  ... -0.002536 -0.007373 -0.000276 -0.002173   
4 -0.004758  0.005961  0.005176  ... -0.003264  0.001135 -0.008510 -0.000614   

       1695      1696      1697      1698      1699      1700  
0 -0.002386 -0.003332 -0.003701 -0.003463 -0.004489 -0.005034  
1 -0.002636 -0.001219  0.000561 -0.004356  0.002053 -0.007237  
2 -0.003341 -0.003316 -0.003289 -0.003263 -0.003236 -0.003209  
3 -0.007754 -0.006247 -0.003583 -0.004043 -0.002472 -0.008282  
4 -0.004077 -0.013175 -0.004247 -0.002622 -0.000083 -0.003888  

[5 rows x 1701 columns]

In [13]:
#normalize(b)
b1=b.apply(lambda x: x/(x**2).sum()**.5, axis=1)
b1.head()

0         1         2         3         4         5         6     \
0  0.009607  0.004595  0.004153  0.001293  0.003809  0.005611  0.012284   
1  0.013683 -0.009277  0.023046 -0.040534  0.000598  0.018640 -0.010568   
2  0.005920  0.006296  0.006659  0.007008  0.007325  0.007399  0.007152   
3  0.001720  0.014365  0.017369  0.013624  0.009649  0.002587  0.012490   
4  0.014017  0.036012  0.006521  0.020120  0.016342  0.011801  0.006702   

       7         8         9     ...      1691      1692      1693      1694  \
0  0.000603  0.005059  0.005881  ... -0.017547 -0.025276 -0.020442 -0.011642   
1 -0.011098 -0.022913  0.014546  ... -0.038060  0.017181 -0.033179 -0.005745   
2  0.006912  0.007250  0.008074  ... -0.018391 -0.018267 -0.018138 -0.018009   
3 -0.012215 -0.003470 -0.014777  ... -0.012008 -0.034912 -0.001307 -0.010292   
4 -0.017573  0.022017  0.019119  ... -0.012055  0.004192 -0.031434 -0.002269   

       1695      1696      1697      1698      1699      1700  
0 -0.012491 -0.017440 -0.019376 -0.018127 -0.023498 -0.026352  
1 -0.009596 -0.004439  0.002042 -0.015857  0.007474 -0.026345  
2 -0.017876 -0.017742 -0.017598 -0.017460 -0.017316 -0.017168  
3 -0.036719 -0.029583 -0.016964 -0.019143 -0.011705 -0.039219  
4 -0.015060 -0.048664 -0.015689 -0.009685 -0.000306 -0.014363  

[5 rows x 1701 columns]

### Normalizing the data for autoenconders

In [14]:
trainx =b1.iloc[:,0:1701]
trainx=trainx.to_numpy()
scaler = MinMaxScaler()
train_x= scaler.fit_transform(trainx)
train_x

array([[0.52029995, 0.48648253, 0.50271907, ..., 0.44043842, 0.38646427,
        0.3660662 ],
       [0.5404537 , 0.41828456, 0.59125601, ..., 0.45256222, 0.55435131,
        0.36610132],
       [0.50206616, 0.4948428 , 0.51446392, ..., 0.44400082, 0.41997146,
        0.41494819],
       ...,
       [0.53347114, 0.50617401, 0.54376633, ..., 0.54671429, 0.45723571,
        0.29587887],
       [0.40518202, 0.42506645, 0.4327896 , ..., 0.53529242, 0.48484028,
        0.46822106],
       [0.59032626, 0.68304793, 0.45215277, ..., 0.25388347, 0.52949914,
        0.43452064]])

In [15]:
# No of Neurons in each Layer 
nb_epoch = 50
batch_size = 50
input_dim = train_x.shape[1] #num of columns, 1701
encoding_dim = 256
hidden_dim1 = int(encoding_dim / 2)
hidden_dim2=int(hidden_dim1/2)
decoding_dim = 256
learning_rate = 1e-7

input_layer = Input(shape=(input_dim, ))
encoder = Dense(encoding_dim, activation="tanh", activity_regularizer=regularizers.l1(learning_rate))(input_layer)
encoder = Dense(hidden_dim1, activation="relu")(encoder)
encoder= Dense(hidden_dim2, activation="relu")(encoder)
decoder = Dense(hidden_dim1, activation='tanh')(encoder)
decoder = Dense(decoding_dim, activation='relu')(decoder)
decoder = Dense(input_dim, activation='relu')(decoder)
autoencoder = Model(inputs=input_layer, outputs=decoder)
autoencoder.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 1701)]            0         
_________________________________________________________________
dense (Dense)                (None, 256)               435712    
_________________________________________________________________
dense_1 (Dense)              (None, 128)               32896     
_________________________________________________________________
dense_2 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_3 (Dense)              (None, 128)               8320      
_________________________________________________________________
dense_4 (Dense)              (None, 256)               33024     
_________________________________________________________________
dense_5 (Dense)              (None, 1701)             

In [16]:
import time
start_time = time.time()
autoencoder.compile(optimizer='adam', loss='mse' )

history = autoencoder.fit(train_x, train_x, epochs=nb_epoch,batch_size=batch_size, shuffle=True,validation_split=0.2,verbose=1)

print("--- %s seconds ---" % (time.time() - start_time))

df_history = pd.DataFrame(history.history) 

Epoch 1/50
792/792 [==============================] - 6s 8ms/step - loss: 0.0777 - val_loss: 0.0658
Epoch 2/50
792/792 [==============================] - 5s 7ms/step - loss: 0.0560 - val_loss: 0.0541
Epoch 3/50
792/792 [==============================] - 5s 7ms/step - loss: 0.0451 - val_loss: 0.0409
Epoch 4/50
792/792 [==============================] - 6s 7ms/step - loss: 0.0339 - val_loss: 0.0322
Epoch 5/50
792/792 [==============================] - 6s 7ms/step - loss: 0.0287 - val_loss: 0.0281
Epoch 6/50
792/792 [==============================] - 6s 7ms/step - loss: 0.0240 - val_loss: 0.0228
Epoch 7/50
792/792 [==============================] - 6s 7ms/step - loss: 0.0207 - val_loss: 0.0196
Epoch 8/50
792/792 [==============================] - 6s 7ms/step - loss: 0.0181 - val_loss: 0.0175
Epoch 9/50
792/792 [==============================] - 6s 7ms/step - loss: 0.0156 - val_loss: 0.0147
Epoch 10/50
792/792 [==============================] - 6s 7ms/step - loss: 0.0140 - val_loss: 0.0133

In [17]:
predictions = autoencoder.predict(train_x)
print(predictions)

[[0.49229616 0.48463395 0.5173408  ... 0.4769416  0.4452365  0.44238222]
 [0.48075932 0.47388604 0.505584   ... 0.5046321  0.4688566  0.46079794]
 [0.49475998 0.48469663 0.51729226 ... 0.47424895 0.4415585  0.4370555 ]
 ...
 [0.48139054 0.47667208 0.50225794 ... 0.5120087  0.4653228  0.45670986]
 [0.45317185 0.44738954 0.48916566 ... 0.5135983  0.46832824 0.4652983 ]
 [0.48621035 0.48038408 0.50995445 ... 0.50247216 0.47839332 0.46677613]]


In [18]:
predictions=pd.DataFrame(predictions)

In [19]:
predictions.head()

0         1         2         3         4         5         6     \
0  0.492296  0.484634  0.517341  0.506389  0.484744  0.481265  0.489983   
1  0.480759  0.473886  0.505584  0.489864  0.467874  0.468942  0.476129   
2  0.494760  0.484697  0.517292  0.506938  0.485008  0.481888  0.491521   
3  0.489838  0.483023  0.516647  0.505553  0.483339  0.482320  0.490332   
4  0.488070  0.482602  0.509153  0.503323  0.482846  0.475292  0.482107   

       7         8         9     ...      1691      1692      1693      1694  \
0  0.487930  0.484355  0.554140  ...  0.402409  0.497639  0.446948  0.441163   
1  0.474600  0.472143  0.539409  ...  0.426597  0.521527  0.467086  0.469160   
2  0.490463  0.486614  0.557285  ...  0.399195  0.495263  0.444294  0.436953   
3  0.486443  0.484766  0.551338  ...  0.401623  0.501924  0.449276  0.444409   
4  0.480994  0.481038  0.552155  ...  0.421064  0.525189  0.467158  0.465159   

       1695      1696      1697      1698      1699      1700  
0  0.402391  0.455650  0.453345  0.476942  0.445237  0.442382  
1  0.415806  0.485761  0.480252  0.504632  0.468857  0.460798  
2  0.400455  0.452804  0.449776  0.474249  0.441559  0.437055  
3  0.407750  0.453941  0.457766  0.477491  0.446515  0.441742  
4  0.425917  0.471404  0.479251  0.499817  0.463592  0.460260  

[5 rows x 1701 columns]

In [20]:
train_x=pd.DataFrame(train_x)

In [21]:
augdata=pd.concat([train_x,predictions],ignore_index=True)

In [22]:
print(augdata.shape)

(99000, 1701)


In [23]:
a1=np.array(dfsub1['Analyte'].values.tolist())
a2=np.array(dfsub2['Analyte'].values.tolist())
a3=np.array(dfsub3['Analyte'].values.tolist())
a4=np.array(dfsub4['Analyte'].values.tolist())
a5=np.array(dfsub5['Analyte'].values.tolist())
a6=np.array(dfsub6['Analyte'].values.tolist())
a7=np.array(dfsub7['Analyte'].values.tolist())
a8=np.array(dfsub8['Analyte'].values.tolist())
a9=np.array(dfsub9['Analyte'].values.tolist())
y=np.concatenate((a1,a2,a3,a4,a5,a6,a7,a8,a9),axis=None)

In [24]:
augy=np.concatenate((a1,a2,a3,a4,a5,a6,a7,a8,a9,a1,a2,a3,a4,a5,a6,a7,a8,a9),axis=None)
augy=pd.DataFrame(augy)

In [25]:
augdata['Analyte']=augy
augdata.tail()

0         1         2         3         4         5         6  \
98995  0.481081  0.473522  0.498453  0.488630  0.466533  0.467711  0.446872   
98996  0.463340  0.468131  0.502735  0.480151  0.459467  0.472508  0.455706   
98997  0.481391  0.476672  0.502258  0.480695  0.456560  0.468710  0.445494   
98998  0.453172  0.447390  0.489166  0.453848  0.434457  0.454864  0.430835   
98999  0.486210  0.480384  0.509954  0.497820  0.469597  0.477264  0.475185   

              7         8         9  ...      1692      1693      1694  \
98995  0.468877  0.458566  0.528123  ...  0.548638  0.488134  0.505453   
98996  0.465760  0.460141  0.525835  ...  0.498857  0.454841  0.439482   
98997  0.474938  0.459544  0.526656  ...  0.511075  0.467222  0.457888   
98998  0.457955  0.449316  0.514599  ...  0.520115  0.474712  0.466283   
98999  0.485645  0.472842  0.531931  ...  0.528153  0.478691  0.475511   

           1695      1696      1697      1698      1699      1700  Analyte  
98995  0.462950  0.512900  0.516031  0.535510  0.500633  0.482448       55  
98996  0.400011  0.468502  0.479060  0.490411  0.446372  0.442844       55  
98997  0.415753  0.491956  0.493354  0.512009  0.465323  0.456710       55  
98998  0.414904  0.490324  0.502745  0.513598  0.468328  0.465298       55  
98999  0.432740  0.486215  0.500474  0.502472  0.478393  0.466776       55  

[5 rows x 1702 columns]

In [26]:
y=augy.to_numpy()
print(np.unique(y,return_counts=True))
#print(type(y))

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55]), array([1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800,
       1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800,
       1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800,
       1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800,
       1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800],
      dtype=int64))


### KNN

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
# We will find by inspection the best k according to the classifier accuracy on the test set
accuracies = []
X=augdata.iloc[:,0:1701]
# We will find by inspection the best k according to the classifier accuracy on the test set
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=0)
start_time=time.time()
for k in range(1, 2, 2):
    # Entrenar el clasificador  con el valor actual de  `k`
    neigh = KNeighborsClassifier(n_neighbors=k)
    neigh.fit(X_train, y_train)

    # Evaluar los modelos e imprimiendo sus predicciones
    score = neigh.score(X_test, y_test)
    print("k=%d, accuracy=%.2f%%" % (k, score * 100))
    accuracies.append(score)
print("time", time.time()-start_time)

k=1, accuracy=85.17%
time 75.50481414794922


In [29]:
X=augdata.iloc[:,0:1701]
X_train, X_test, Y_train, Y_test = train_test_split(X,y, test_size=0.2,random_state=0)
X_train=pd.DataFrame(X_train)
X_test=pd.DataFrame(X_test)
X_train.to_csv("c:/Users/eacun/NRL/NRLDataset/train/Subs/X_train.csv",index=False,header=False)
X_test.to_csv("c:/Users/eacun/NRL/NRLDataset/test/Subs/X_test.csv",index=False,header=False)

In [31]:
np.savetxt('c:/Users/eacun/NRL/NRLDataset/train/y_train.csv', Y_train) 
np.savetxt('c:/Users/eacun/NRL/NRLDataset/test/y_test.csv', Y_test) 

### SVM

In [85]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, f1_score, precision_score, roc_auc_score
from sklearn.preprocessing import StandardScaler
from sklearn import svm
import time
#y=dfsub1['Analyte']
#print(y.value_counts())
X=augdata.iloc[:,0:1701]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=0)
scaler = StandardScaler()
scaler.fit(X_train)
X_train= scaler.transform(X_train)
X_test = scaler.transform(X_test)
#clf=svm.svmSVC(max_iter=2000)
start_time = time.time()
clf=svm.SVC()
clf.fit(X_train, y_train) 
print("The accuracy is=",clf.score(X_test,y_test))
print("--- %s seconds ---" % (time.time() - start_time))
predictions = clf.predict(X_test)
#prob4=pd.DataFrame(clf.predict_proba(X_test))
#a=prob4.max(axis=1)
#print('Probability of classification',(a[a>.50].shape[0])/prob2.shape[0])
print("F1-score is=",f1_score(y_test,predictions, average="weighted"))
print("precision=",precision_score(y_test,predictions,average="weighted"))

The accuracy is= 0.7803535353535354
--- 5423.509306192398 seconds ---
F1-score is= 0.8060200201258876
precision= 0.8537518307564993


### Logistic Regression

In [ ]:
### DO NOt RUn more tha 40 iterations
from sklearn.linear_model import LogisticRegression
import time
X=augdata.iloc[:,0:1701]
#model.fit(X,y)
#model.score(X,y)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=0)
start_time = time.time()
model = LogisticRegression(solver="newton-cg",multi_class="multinomial",max_iter=40)
model.fit(X_train,y_train)
#Calculating  metrics of prediction
predictions = model.predict(X_test)
#print(predictions)
#print("F1-score is=",f1_score(y_test,predictions, average="weighted"))
#print("precision=",precision_score(y_test,predictions,average="weighted"))
print("The accuracy is=",model.score(X_test,y_test))
print("--- %s seconds ---" % (time.time() - start_time))

### MLP

In [ ]:
import tensorflow as tf
from tensorflow import keras
import os
import tempfile
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, f1_score, precision_score, roc_auc_score
import keras
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.utils import to_categorical
import time

In [ ]:
# Configuration options
feature_vector_length = 1701
num_classes = 55
x=augdata.iloc[:,0:1701].to_numpy()
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=0.2,random_state=0)
# Convert target classes to categorical ones
ytrain=Y_train-1
ytest=Y_test-1
Y_train = to_categorical(ytrain, num_classes)
Y_test = to_categorical(ytest, num_classes)
print('Train dimension:')
print(X_train.shape)
print('Test dimension:')
print(Y_test.shape)

In [ ]:
# Set the input shape
input_shape = (feature_vector_length,)
print(f'Feature shape: {input_shape}')

# Create the model
model = Sequential()
#model.add(Dropout(0.3, input_shape=input_shape))
model.add(Dense(300, input_shape=input_shape, activation='relu'))
#model.add(Dropout(0.3))
model.add(Dense(200, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))
model.summary()

In [ ]:
# Configure the model and start training
import time
start_time = time.time()
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
baseline_history=model.fit(X_train, Y_train, epochs=100, batch_size=150, verbose=1, validation_split=0.2)

In [ ]:
print("Training time:---  %s seconds ---" % (time.time() - start_time))
#Test the model after training
start_time=time.time()
test_results = model.evaluate(X_test, Y_test, verbose=1)
print(test_results)
print(f'Test results - Loss: {test_results[0]} - Accuracy: {test_results[1]}%')
print("--- %s seconds ---" % (time.time() - start_time))

### CNN

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Conv1D, Flatten, MaxPooling1D, Dropout
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.datasets import load_iris
from numpy import unique
import pandas as pd
import numpy as np
import time
import keras

In [ ]:
x=augdata.iloc[:,0:1701].to_numpy()
x = x.reshape(x.shape[0], x.shape[1], 1)
print(x.shape)
y=y-1
#print(unique(y))
#print(unique(y).sum())

xtrain, xtest, ytrain, ytest=train_test_split(x, y, test_size=0.2)


In [ ]:
model = Sequential()
model.add(Conv1D(32, 3, activation="relu", input_shape=(1701,1)))
model.add(Dense(64, activation="relu"))
model.add(MaxPooling1D(pool_size=3))
model.add(Dropout(0.5))
model.add(Conv1D(32, 3, activation="relu", input_shape=(1701,1)))
model.add(Dense(64, activation="relu"))
model.add(MaxPooling1D(pool_size=3))
model.add(Dropout(0.5))
model.add(Flatten())
model.add(Dense(55, activation = 'softmax'))
start_time = time.time()
model.compile(loss = 'sparse_categorical_crossentropy', optimizer = "adam", metrics = ['accuracy'])
model.summary()
baseline_history=model.fit(xtrain, ytrain, epochs=30, batch_size=256, verbose=1, validation_split=0.2)
#model.fit(xtrain, ytrain, batch_size=256,epochs=25,  validation_split=.2, verbose=1)
acc = model.evaluate(xtrain, ytrain)
print("Loss:", acc[0], " Accuracy:", acc[1])
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
start_time = time.time()
#Test the model after training
start_time=time.time()
test_results = model.evaluate(xtest, ytest, verbose=1)
print(test_results)
print(f'Test results - Loss: {test_results[0]} - Accuracy: {test_results[1]}%')
print("--- %s seconds ---" % (time.time() - start_time))